#!/usr/bin/env bash
set -e

source ~/text/ven/ai/bin/activate
export PICOCLAW_AUDIO_CARD_NAME="${PICOCLAW_AUDIO_CARD_NAME:-rockchipnau8822}"
export PICOCLAW_INPUT_CARD_NAME="${PICOCLAW_INPUT_CARD_NAME:-rockchipnau8822}"
export PICOCLAW_OUTPUT_CARD_NAME="${PICOCLAW_OUTPUT_CARD_NAME:-rockchipnau8822}"
export PICOCLAW_INPUT_SAMPLE_RATE="${PICOCLAW_INPUT_SAMPLE_RATE:-48000}"
export PICOCLAW_OUTPUT_SAMPLE_RATE="${PICOCLAW_OUTPUT_SAMPLE_RATE:-48000}"
export PICOCLAW_INPUT_CHANNEL="${PICOCLAW_INPUT_CHANNEL:-best}"
export PICOCLAW_ASR_THREADS="${PICOCLAW_ASR_THREADS:-2}"
export PICOCLAW_TTS_THREADS="${PICOCLAW_TTS_THREADS:-2}"
export PICOCLAW_ASR_QUEUE_CHUNKS="${PICOCLAW_ASR_QUEUE_CHUNKS:-12}"
export PICOCLAW_ASR_BLOCK_SECONDS="${PICOCLAW_ASR_BLOCK_SECONDS:-0.05}"
export PICOCLAW_OPENCV_THREADS="${PICOCLAW_OPENCV_THREADS:-1}"
export PICOCLAW_DETECT_INTERVAL="${PICOCLAW_DETECT_INTERVAL:-0.06}"
cd "$(dirname "$0")"
exec python3 skill_realtime_listener.py
